version: "3.8"

services:
  backend:
    image: maven:3.9-eclipse-temurin-17
    container_name: enjoytrip-backend-dev
    working_dir: /app
    command: mvn spring-boot:run
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ./target/classes:/app/target/classes
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7.2
    container_name: redis-dev
    ports:
      - "6379:6379"
