spring:
  application:
    name: enjoytrip-05

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      idle-timeout: 300000
      minimum-idle: 3
      maximum-pool-size: 5
      connection-timeout: 600000

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  devtools:
    restart:
      enabled: true

  # Spring AI
  ai:
    openai:
      api-key: ${OPENAI_SECRET}
      base-url: https://api.openai.com
      chat:
        model: ${OPENAI_MODEL}


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.ssafy.enjoytrip.**.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.ssafy.enjoytrip: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

jwt:
  secret: ${JWT_SECRET}

overpass:
  url: https://overpass.kumi.systems/api/interpreter
