spring:
  application:
    name: enjoytrip-05

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      idle-timeout: 300000
      minimum-idle: 3
      maximum-pool-size: 5
      connection-timeout: 600000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

#  springdoc:
#    api-docs:
#      path: /v3/api-docs
#    swagger-ui:
#      path: /swagger-ui.html

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.ssafy.enjoytrip.**.dto
  config-location: classpath:mybatis-config.xml


logging:
  level:
    root: INFO
    com.ssafy.enjoytrip: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE